version: 2.1
executors:
  unity:
    docker:
      # https://hub.docker.com/r/gableroux/unity3d/tags
      - image: gableroux/unity3d:2018.2.3f1
  unity-android:
    docker:
      - image: gableroux/unity3d:2018.2.21f1-android 
commands:
  unity-build:
    description: "Build Unity Project"
    parameters:
      platform:
        type: string
        default: "StandaloneWindows64"
      buildPath:
        type: string
        default: "./bin-win64/"
      buildName:
        type: string
        default: "CISample"
    steps:
      - run:
          name: Building Unity Project
          command: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -customBuildPath << parameters.buildPath >> -customBuildTarget << parameters.platform >> -customBuildName << parameters.buildName >> -executeMethod BuildCommand.PerformBuild
#          command: xvfb-run -a /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile /root/project/UnityBuildLog.log -customBuildPath /root/project/Build -customBuildTarget StandaloneWindows64 -executeMethod BuildCommand.PerformBuild
#          command: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -noUpm -logFile -projectPath . -buildWindows64Player ./bin-win64/CISample.exe
          no_output_timeout: 60m

environment:
      BUILD_NAME: ExampleProjectName
      BUILD_TARGET: StandaloneLinux64
jobs:
  build-test:
    executor: unity-android
    steps:
      - checkout
      - run: mkdir -p /root/project/Build
      - run: mkdir -p /root/.cache/unity3d
      - run: mkdir -p /root/.local/share/unity3d/Unity/
      - run: openssl aes-256-cbc -d -in .circleci/Unity_v2018.x.ulf-cipher -k 123 >> .circleci/Unity_v2018.x.ulf
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .circleci/Unity_v2018.x.ulf || exit 0
      - unity-build:
          platform: "Android"
          buildPath: "./bin-android/"
          buildName: "./bin-android/"
#      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .circleci/Unity_v2018.x.ulf || exit 0
#      - run:
#        /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -customBuildPath ./caches -customBuildTarget StandaloneWindows64 -executeMethod BuildCommand.PerformBuild
#        no_output_timeout: 30m
      - store_artifacts:
          path: ./bin-android
workflows:
  version: 2
  build:
    jobs:
      - build-test
