version: 2.1
executors:
  unity:
    docker:
      # https://hub.docker.com/r/gableroux/unity3d/tags
      - image: gableroux/unity3d:2018.2.21f1
environment:
      BUILD_NAME: ExampleProjectName
      BUILD_TARGET: StandaloneLinux64
jobs:
  build-test:
    executor: unity
    steps:
      - checkout
      - run: mkdir -p /root/.cache/unity3d
      - run: openssl aes-256-cbc -d -in .circleci/Unity_v2018.x.ulf-cipher -k 123 >> .circleci/Unity_v2018.x.ulf
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -manualLicenseFile .circleci/Unity_v2018.x.ulf || exit 0
      - run: /opt/Unity/Editor/Unity -quit -batchmode -nographics -silent-crashes -logFile -customBuildPath ./caches -customBuildTarget StandaloneWindows64 -executeMethod BuildCommand.PerformBuild
      - no_output_timeout: 60m
      - when
      - store_artifacts:
          path: ./caches
workflows:
  version: 2
  build:
    jobs:
      - build-test
